spring:
  profiles:
    active:
    - dev
  application:
    name: ai-expense-tracker

  jpa:
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect

  flyway:
    locations: classpath:db/migration
    validate-on-migrate: true
    baseline-on-migrate: true

spring doc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /v3/api-docs

server:
  port: 8080

bcrypt:
  strength: 12

jwt:
  secret-key: ${JWT_SECRET}
  access-token-expiration: 900000
  refresh-token-expiration: 604800000