INSERT INTO categories (
    id,
    name,
    icon,
    color,
    type,
    user_id,
    created_at,
    updated_at
)
VALUES
    (
        gen_random_uuid(),
        'Food & Dining',
        'utensils',
        '#FF6B6B',
        'SYSTEM',
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        gen_random_uuid(),
        'Transport',
        'car',
        '#4DABF7',
        'SYSTEM',
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        gen_random_uuid(),
        'Shopping',
        'shopping-bag',
        '#CC5DE8',
        'SYSTEM',
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        gen_random_uuid(),
        'Bills & Utilities',
        'receipt',
        '#FFA94D',
        'SYSTEM',
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        gen_random_uuid(),
        'Entertainment',
        'film',
        '#845EF7',
        'SYSTEM',
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        gen_random_uuid(),
        'Health',
        'heart-pulse',
        '#20C997',
        'SYSTEM',
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        gen_random_uuid(),
        'Education',
        'graduation-cap',
        '#5C7CFA',
        'SYSTEM',
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        gen_random_uuid(),
        'Travel',
        'plane',
        '#22B8CF',
        'SYSTEM',
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    ),
    (
        gen_random_uuid(),
        'Other',
        'circle-ellipsis',
        '#868E96',
        'SYSTEM',
        NULL,
        CURRENT_TIMESTAMP,
        CURRENT_TIMESTAMP
    );